### ISSUE TITLE
Update to 0.0.26 fails with 404

### ISSUE THREAD

**Issue by timn** [crowdsecurity/home-assistant-addons#37]
When trying to upgrade from 0.0.25 to 0.0.26 in HomeAssistant 2023.5.2 I get the following error:
```
Can't install ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26/json: Not Found ("No such image: ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26")
```
After uninstalling to see if that helps I cannot install again (with the same message).

An idea how to resolve that?

**Comment by oscarsiles** [comment]
It looks like the ARM64 image is missing (same error on my RPi 4).

**Comment by Didel** [comment]
I get the same error, on a Raspberry Pi 4 as well. The recent updates by @he2ss look like they could be the cause of this (some changes in the build process and certain URL’s that have changed).

**Comment by jpartain89** [comment]
+1 on this issue, here...

**Comment by Jonesnetwork** [comment]
+1 here with the same issue

**Comment by scoudibou** [comment]
+1 same issue with RPi 4, even with docker pull directly 

~ # docker pull ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26
v0.0.26: Pulling from crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by he2ss** [comment]
Hi,

Thanks, guy for spotting this. 
Indeed there was an issue with the bouncer release, I made a quick fix to get the latest release working.
But seems still not working (maybe I missed something during the QA). I'll definitely have a look asap.

**Comment by he2ss** [comment]
I released a new version.
Can one of you guys test again to see if it's working now?

Thanks.

**Comment by Didel** [comment]
@he2ss It seems like HA isn't able to find the newer version (perhaps because it still has the same 0.0.26 version number)? I have restarted HA, forced the 'Check for updates' manually, and while it still sees the v0.0.26 update (as I am currently on 0.0.25), I am still not able to update (having the same error as above).

**Comment by Didel** [comment]
@he2ss Even with the 'updated' version, I still get (almost) the same error:

```
Error updating Crowdsec Firewall Bouncer: Can't install ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26-ha1: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26-ha1/json: Not Found ("No such image: ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26-ha1"
```

**Comment by he2ss** [comment]
Hum very weird because I'm also running a HA OS but using a virtual machine (amd64). And I'm able to DL the new version.
The image `ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer:v0.0.26-ha1` exists. You can manually pull it from the HA shell; it should work. 
There is maybe an issue with the HA local cache, I can't explain for now.

**Comment by scoudibou** [comment]
@he2ss it's working now (ha2). Thank you very much

**Comment by LaurenceJJones** [comment]
Closing due to resolution. Please reopen a new issue if the issue persists.
